apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightmock
  namespace: entreprise-tools
  labels:
    app.kubernetes.io/name: lightmock
    app.kubernetes.io/component: server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lightmock
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lightmock
        app.kubernetes.io/component: server
    spec:
      containers:
        - name: lightmock
          image: lightmock:latest
          ports:
            - containerPort: 7342
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: lightmock-config
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 200m
              memory: 64Mi
          readinessProbe:
            httpGet:
              path: /api/config
              port: http
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/config
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: lightmock-data
      terminationGracePeriodSeconds: 10
