apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: entreprise-tools
resources:
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - upstream.yaml
  - routetable.yaml
  - virtualservice.yaml
