apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: mimicway
  labels:
    app.kubernetes.io/name: mimicway
    app.kubernetes.io/component: routing
spec:
  kube:
    serviceName: mimicway
    serviceNamespace: mimicway
    servicePort: 80
