apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: lightmock
  labels:
    app.kubernetes.io/name: lightmock
    app.kubernetes.io/component: routing
spec:
  kube:
    serviceName: lightmock
    serviceNamespace: lightmock
    servicePort: 80
